spring.application.name=Climalert
weather.api.key=9b11bcaf49364a56a6620611260307
weather.api.city=CABA
spring.datasource.url=jdbc:h2:file:./data/climalert
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true